"""Shared Home Assistant entities for UniFi Announcer."""
from __future__ import annotations

from homeassistant.helpers import device_registry as dr
from homeassistant.helpers.device_registry import DeviceEntryType, DeviceInfo
from homeassistant.helpers.update_coordinator import CoordinatorEntity

from .const import DOMAIN


def target_display_name(target: str | None, *, is_group: bool = False) -> str:
    """Return a useful Home Assistant device name for an API target."""
    if target and target.strip() and target.strip().lower() != "default":
        return target.replace("_", " ").strip().title()
    return "Chime Group" if is_group else "Protect Smart Chime"


def migrate_generated_names(entry, coordinator) -> None:
    """Replace names generated by older releases without overriding user names."""
    device_registry = dr.async_get(coordinator.hass)
    service = device_registry.async_get_device(
        identifiers={(DOMAIN, entry.data["url"])}
    )
    if service and service.name_by_user is None and service.name == entry.title:
        device_registry.async_update_device(
            service.id, name=f"{entry.title} Service"
        )

    for target, chime_id, is_group in configured_targets(coordinator):
        if not chime_id or is_group:
            continue
        device = device_registry.async_get_device(
            identifiers={(DOMAIN, str(chime_id))}
        )
        if device and device.name_by_user is None and device.name == target:
            device_registry.async_update_device(
                device.id, name=target_display_name(target)
            )


def configured_targets(coordinator) -> list[tuple[str, str | None, bool]]:
    """Return (target name, chime id, is_group) tuples from coordinator state."""
    data = coordinator.data or {}
    chime_data = data.get("chimes", {})
    targets: list[tuple[str, str | None, bool]] = []
    for chime in chime_data.get("chimes", []):
        name = str(chime.get("name") or chime.get("id") or "chime")
        targets.append((name, chime.get("id"), False))
    for group in (chime_data.get("groups") or {}):
        targets.append((str(group), None, True))
    return targets


class UniFiAnnouncerEntity(CoordinatorEntity):
    """Base coordinator-backed entity."""

    _attr_has_entity_name = True

    def __init__(self, entry, coordinator, target: str | None = None,
                 chime_id: str | None = None, is_group: bool = False) -> None:
        service_identifier = (DOMAIN, entry.data["url"])
        dr.async_get(coordinator.hass).async_get_or_create(
            config_entry_id=entry.entry_id,
            identifiers={service_identifier},
            name=f"{entry.title} Service",
            manufacturer="UniFi Announcer",
            model="Local announcement service",
            entry_type=DeviceEntryType.SERVICE,
        )
        migrate_generated_names(entry, coordinator)
        super().__init__(coordinator)
        self.entry = entry
        self.runtime = entry.runtime_data
        self.target = target
        self.chime_id = chime_id
        self.is_group = is_group

    @property
    def entity_key(self) -> str:
        """Stable key: physical entities follow Protect ID, groups follow group name."""
        return str(self.chime_id or self.target or "service")

    @property
    def device_info(self) -> DeviceInfo:
        service_identifier = (DOMAIN, self.entry.data["url"])
        if self.target and self.chime_id and not self.is_group:
            return DeviceInfo(
                identifiers={(DOMAIN, str(self.chime_id))},
                name=target_display_name(self.target),
                manufacturer="Ubiquiti",
                model="Protect Smart Chime",
                via_device=service_identifier,
            )
        return DeviceInfo(
            identifiers={service_identifier},
            name=f"{self.entry.title} Service",
            manufacturer="UniFi Announcer",
            model="Local announcement service",
            entry_type=DeviceEntryType.SERVICE,
        )
